baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Matthew Montesano'
theme = 'hugo-bootstrap'
navbarBgColorClass = 'secondary'


[[menu.main]]
    name = "About"
    pre = "<i class='fa-solid fa-circle-info'></i>"
    weight = -90
    identifier = "about"
    url = "/about"

[[menu.main]]
    name = "Papers"
    pre = "<i class='fa fa-book'></i>"
    weight = -10
    identifier = "papers"
    url = "/papers"

[[menu.main]]
    name = "Talks"
    pre = "<i class='fa-solid fa-person-chalkboard'></i>"
    weight = 10
    identifier = "talks"
    url = "/talks"

    