baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Matthew Montesano'
theme = 'hugo-bootstrap'


[[menu.main]]
    name = "LinkedIn"
    pre = "<i class='fa-brands fa-linkedin'></i>"
    weight = -90
    identifier = "linkedin"
    url = "https://www.linkedin.com/in/matthew-montesano-40a83253/"

[[menu.main]]
    name = "Email me"
    pre = "<i class='fa-solid fa-envelope'></i>"
    weight = -10
    identifier = "email"
    url = "mailto:montesano@gmail.com"